{lib}: {
  username = "manu";
  userfullname = "Emmanuel Vargas";
  useremail = "emmanuel.vargas@gmail.com";
  networking = import ./networking.nix {inherit lib;};
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....w4NiIh5VZ1PK2xVIBE7570$0KzFUCpIYRzhqSKqyGMASO1fEuN6R7xBX.56ssXeWV7";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx`
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJc9R8O3PZTpwi6RIqci41CnGuwjs1NxYxpoJ5ZV4LDp vargas@lonitx-vm-ubuntu"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINjaVclo7DZzoNgTowU5PQaTIXclfhTO9yizIIFjd25Y emmanuel.vargas@iress.com"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEG9sbnm7GF7LQ/csbk729YUlu89TSY2mLDmla/tgKGc emmanuel.vargas@gmail.com"
  ];
}
